services:
  api:
    build: .
    container_name: energy-api
    command: uvicorn energy_forecasting.api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./mlflow_artifacts_tmp:/app/mlflow_artifacts_tmp
    env_file:
      - .env

  dashboard:
    build: .
    container_name: energy-dashboard
    command: streamlit run streamlit_app/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./mlflow_artifacts_tmp:/app/mlflow_artifacts_tmp
    env_file:
      - .env
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000